// ╔═══════════════════════════════════════╗
// ║  @Ultr                                ║
// ║  Multi Moving Averages & CrossOver    ║
// ║  © LuxAlgo                            ║
// ╚═══════════════════════════════════════╝

//@version=5
indicator("Multi Moving Average & CrossOver (@Ultr)", shorttitle = "MAs CrossOver(@Ultr.)", overlay = true)

//  ═════════
//  Multi CMA
//  Constants
//  ═════════

// Color
color colorZero = color.new(#e91e63, 46)  // color Amarillo #eedd45
color colorFirs = color.new(#33ffac, 46)  // color Menta	#33ffac
color colorSeco = color.new(#eedd45, 46)  // color Fucxia	#e91e63
color colorThir = color.new(#0034c5, 80)  // color Azul		#0034c5
color colorCuar = color.new(#9598a1, 92)  // color Gris		#9598a1
color colorFift = color.new(#e65100, 46)  // color Naranja	#e65100

colorBuy80          = color.new(#33ffac, 80)
colorSell80         = color.new(#e91e63, 80)
color colorBuy60    = color.new(#33ffac, 60)
color colorSell60   = color.new(#e91e63, 60)
colorBuy40          = color.new(#33ffac, 40)
colorSell40         = color.new(#e91e63, 40)
colorBuy20          = color.new(#33ffac, 20)
colorSell20         = color.new(#e91e63, 20)

// Indicador
int length8   = input(8, title   = "8 Periodos")
int length21  = input(21, title  = "21 Periodos")
int length55  = input(55, title  = "55 Periodos")
int length100 = input(100, title = "100 Periodos")
int length200 = input(200, title = "200 Periodos")

length10 = input(10)
length13 = input(13)
length20 = input(20)
length30 = input(30)
length34 = input(34)
length40 = input(40)
length50 = input(50)

//  ═════════
//  Multi CMA
//  Inputs - Options
//  ════════════════

string optionMa	= input.string("SMA", "Tipo de MM", options = ["EMA", "SMA", "RMA", "WMA", "VWMA"])

//  ═════════
//  Multi CMA
//  Functions
//  ══════

ma(source, length, type) =>
    type == "SMA" ? ta.sma(source, length) :    // Media Movil Simple
     type == "EMA" ? ta.ema(source, length) :   // Media Movil Exponencial
     type == "RMA" ? ta.rma(source, length) :   // Media Movil
     type == "WMA" ? ta.wma(source, length) :   // Media Movil Ponderada
     type == "VWMA" ? ta.vwma(source, length) : // Media Movil Ponderada por volumen
     na

//  ═════════
//  Multi CMA
//  Instancias
//  ══════════
ma8  = ma(close, length8, optionMa)
//  plot(ma8, "MA 8", colorZero, linewidth = 1)
ma10 = ma(close, length10, optionMa)
ma13 = ma(close, length13, optionMa)
ma20 = ma(close, length20, optionMa)
ma21 = ma(close, length21, optionMa)
ma30 = ma(close, length30, optionMa)
ma34 = ma(close, length34, optionMa)
ma40 = ma(close, length40, optionMa)
ma50 = ma(close, length50, optionMa)
//  plot(ma21, "MA 21", colorFirs, linewidth = 1)
ma55 = ma(close, length55, optionMa)
//  plot(ma55, "MA 55", colorSeco, linewidth = 1)
ma100 = ma(close, length100, optionMa)
ma200 = ma(close, length200, optionMa)

//  ═════════
//  Multi CMA
//  Display
//  ═══════

plot(ma100, "MA 100", colorThir, linewidth = 2)
plot(ma200, "MA 200", colorCuar, linewidth = 1, style = plot.style_area)

maPlot8  = plot(ma8,  "MA 8",  color = na)
maPlot10 = plot(ma10, "MA 10", color = na)
maPlot13 = plot(ma13, "MA 13", color = na)
maPlot20 = plot(ma20, "MA 20", color = na)
maPlot21 = plot(ma21, "MA 21", color = na)
maPlot30 = plot(ma30, "MA 30", color = na)
maPlot34 = plot(ma34, "MA 34", color = na)
maPlot40 = plot(ma40, "MA 40", color = na)
maPlot50 = plot(ma50, "MA 50", color = na)
maPlot55 = plot(ma55, "MA 55", color = na)

//  ═════════
//  Multi CMA
//  CrossOver
//  ═════════

// CrossOver shadow
// 8 MA
color maCrossOver8 = ma8 > ma21 ? colorBuy80 : colorSell60
fill(maPlot8, maPlot21, maCrossOver8, "CrossOver 8")

// 20 MA
color maCrossOver21 = ma8 > ma55 ? colorBuy80 : colorSell80
fill(maPlot8, maPlot55, maCrossOver21, "CrossOver 21")

// CrossOver Line
bool maRising  = ta.rising(ma10, 1)
color crossMa = maRising ? colorBuy40 : colorSell40
plot(ma21, "Operativa", crossMa, 4)

//  Degradado

//  float maHeight = ta.percentrank(ma21, 100)
//  float transparency = math.min(80, 100 - maHeight)

//  MA degradado
//  plot(ma, "Degradado", color.new(colorFirs, transparency), 2)

//  Marcas Operativas
//  buyCond = ta.crossover(ma10, ma21)
//  sellCond = ta.crossunder(ma10, ma21)

//  plotshape(series = buyCond, title = "Compra", style = shape.triangleup, location = location.belowbar, color = colorBuy, text = "Buy", size = size.tiny)
//  plotshape(series = sellCond, title = "Venta", style = shape.triangledown, location = location.abovebar, color = colorSell, text = "Sell", size = size.tiny)